site_name: CivicActions Design Practice
nav:
  - Home: index.md
  - Contributing: ../CONTRIBUTING.md
  - Governance: ../GOVERNANCE.md
  - License (content): ../LICENSE-content
  - License (code): ../LICENSE
theme:
  name: mkdocs
docs_dir: docs
